name:        th-env
version:     0.1.1
synopsis:    Template Haskell splices that expand to an environment variable

description: TH splices that expand to an environment variable value.
             Can be used to embed build-time parameters in your application.

github:      dzhus/th-env
license:     BSD3
author:      Dmitry Dzhus
maintainer:  dima@dzhus.org
category:    Template Haskell

extra-source-files:
  - CHANGELOG.md
  - README.md

ghc-options:
  - -Wall
  - -Wcompat

dependencies:
  - base < 5

library:
  source-dirs: src
  dependencies:
    - template-haskell
    - th-compat

tests:
  readme:
    main: README.lhs
    ghc-options:  -pgmL markdown-unlit
    dependencies:
      - markdown-unlit
      - th-env
